[package]
name = "julia-sets"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
minifb = "0.24.0"
num-complex = "0.4.3"
rand = "0.8.5"
rayon = "1.7.0"
